Repository kishanpatel97/APPT, pull requests merged in 2021-12, with the labels that each got.

#21 Initial server commit
  server/package-lock.json
  server/package.json
  server/server.ts
  server/tsconfig.json
Labels: enhancement, backend

#22 Client package.json version upgrades
  client/package-lock.json
  client/package.json
  client/yarn.lock
Labels: frontend

#25 configure tailwind css
  client/package-lock.json
  client/package.json
  client/src/index.css
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement, frontend

#28 Appt 9: Create controllers for Appointments
  server/config/jwt.config.ts
  server/controllers/appt.controller.ts
  server/controllers/user.controller.ts
  server/interfaces/appointment.interface.ts
  server/interfaces/user.interface.ts
  server/models/appt.model.ts
  server/models/user.model.ts
  server/package.json
  server/routes/appt.routes.ts
  server/routes/routes.config.ts
  server/routes/user.routes.ts
  server/server.ts
  server/yarn.lock
Labels: enhancement, backend

#40 modal component for dashboard
  client/src/App.tsx
  client/src/components/modal.tsx
Labels: enhancement, frontend

#41 created card component, modified index css
  client/src/components/card.tsx
  client/src/index.css
Labels: frontend

#43 appointment list with fetch for data from database and update card to…
  client/src/App.tsx
  client/src/components/appointmentList.tsx
  client/src/components/card.tsx
  server/interfaces/appointment.interface.ts
  server/interfaces/user.interface.ts
  shared/interfaces/appointment.interface.ts
Labels: frontend

#45 integrate modal into appointmentList
  client/src/App.tsx
  client/src/components/appointmentList.tsx
  client/src/components/card.tsx
  client/src/components/modal.tsx
  client/src/index.css
  client/src/view/ModalAdd.tsx
  server/config/jwt.config.ts
  server/controllers/appt.controller.ts
  server/package.json
  server/routes/appt.routes.ts
  server/server.ts
  server/yarn.lock
  shared/interfaces/appointment.interface.ts
Labels: enhancement, frontend, backend

#47 added max value for time input so year would stop at 4 digits
  client/src/components/modal.tsx
Labels: bug, frontend

#48 added star rating component to card, added to CSS
  client/src/components/card.tsx
  client/src/components/starrating.tsx
  client/src/index.css
Labels: enhancement, frontend
